### ISSUE TITLE
How "slower"/"faster" is dynamic vs static?

### ISSUE THREAD

**Issue by patrickptasinskift** [lambci/crambda#4]
Hey. I was reading the readme (https://github.com/lambci/crambda#static-binary-easy-but-larger-and-slower) and you mention that static is slower. But is it slower to build or slower to run? I would think that static is faster to run, but might be slower to build but wanted to confirm what you meant

**Comment by mhart** [comment]
I meant slower to run actually – because the static binary is much larger, and larger function size means slower cold starts.

**Comment by ipepe** [comment]
> I meant slower to run actually – because the static binary is much larger, and larger function size means slower cold starts.

That makes sense, thanks!

**Comment by ipepe** [comment]
> I meant slower to run actually – because the static binary is much larger, and larger function size means slower cold starts.

That makes sense, thanks!

**Comment by patrickptasinskift** [comment]
That makes sense, thanks!
